### ISSUE TITLE
Question: architectural details for a simple textx editor

### ISSUE THREAD

**Issue by goto40** [textX-tools/textX-languageserver#5]
Hello @danixeee (also hello @igordejanovic)!

First of all I want to thank you for your excellent work!

I am playing around to provide a minimal editor support for small project files. However, I am not an expert with editor architectures.

I would like to get a hint (**a link into your textX-languageserver architecture**), how to computational efficiently access information to be able to provide, e.g, parse trees for "half-parsed" models (e.g., when I just type a model and the second half is missing, which makes the model text not parsable completely).

I would also like to have your expertise, if the experiment could possibly yield a usable editor... 
https://github.com/goto40/textX-gui-experiment/blob/master/docs/editor.md
I am very unsure about it, is some points is seems not to be the right way...

**Comment by danixeee** [comment]
Hello @goto40.

`textX-languageserver` implements [Language Server Protocol](https://microsoft.github.io/language-server-protocol/specification) and its basic idea is to separate language support (code completion, diagnostics, ...) from different editors.

By the end of November, we will have python `Language Server Framework` (LSF) and able to create language servers in just few lines of code (maybe it will be interesting for you).
Also, plan is to rewrite `textX-languageserver` and create it on top of LSF. You can take a look at current [features](https://www.youtube.com/watch?v=vAP5c7pwWiY).

I think you are not able to work with "half-parsed" models, since `mm.model_from_file` and `mm.model_from_str` methods will raise exception for non valid models.

**Comment by goto40** [comment]
Hi!

Thank you for your response. I think I drop the experiment I started. I am looking forward to see how your project evolves...

I would like something simple like metamodel.open_editor()... But maybe this needs some more time.
Best,
Pierre

**Comment by danixeee** [comment]
Hi Pierre,

Our plan is to create `language server` for `textX` from scratch using python language server framework (after becoming open-source). That way we will be able to focus on features for textX and not worry about language server protocol implementation.

We will create a new repository with CI/CD and backlog issues and your contribution will be very helpful since you showed interest in this field.

Plan is to integrate [viewX](https://github.com/textX-tools/viewX-vscode) into the extension, also (great project; try it out if you haven't already).

Best,
Daniel

**Comment by igordejanovic** [comment]
Hi all,

We have a new developer on board (@AirmiX) who will be working on a minimal web-based editor for textX based languages as a part of his master thesis.

The idea is to produce/generate an editor with syntax highlighting/folding/outline, and optionally communication with [LSP for textX](https://github.com/textX-tools/textX-languageserver) if available, from the textX grammar. The editor should be simple enough to be usable with little, if any, setup. The goal for this editor is to be used during grammar development but also to be usable as embeddable editor for desktop application and, of course, an editor for web apps.

**Comment by goto40** [comment]
Sounds very good. Maybe you could also have a look on multi file models and
multi Metamodell support...

Igor Dejanović <notifications@github.com> schrieb am Di., 16. Okt. 2018,
17:26:

**Comment by igordejanovic** [comment]
Yes, multi-meta-model support is also on the table :)

**Comment by danixeee** [comment]
Sounds great.

@AirmiX Welcome and happy coding! :)

**Comment by AirmiX** [comment]
Thank you! :)
